In [99]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB

In [3]:
from sklearn.model_selection import train_test_split

In [104]:
# mydata
path = "mydata.xlsx"
data = pd.read_excel(path)

In [105]:
mydata = data.copy()

In [107]:
mydata

id  kategori_satu kategori_dua kategori_tiga kategori_empat  target
0    1         lulus       tinggi         besar        panjang   bagus
1    2   tidak_lulus       rendah         kecil         pendek   tidak
2    3   tidak_lulus       sedang        sedang         sedang   bagus
3    4   tidak_lulus       tinggi        sedang        panjang  netral
4    5         lulus       tinggi         besar        panjang   bagus
5    6   tidak_lulus       rendah         kecil         sedang   tidak
6    7   tidak_lulus       rendah         kecil        panjang  netral
7    8         lulus       rendah         kecil         sedang  netral
8    9   tidak_lulus       tinggi        sedang        panjang   bagus
9   10         lulus       rendah         kecil         pendek   bagus

In [ ]:
mydata.append(mydata2, ignore_index=True)

<h2>pembagian data</h2>

In [110]:
data_training = mydata.iloc[:, :-1]

In [111]:
data_target = mydata.iloc[:, -1]

In [112]:
data_test = data_training.iloc[1, :].values

In [120]:
# menggabungkan data array masuk ke dataframe pandas
data_gabung = data_training.copy()
data_gabung.loc[len(data_gabung)] = data_test

In [121]:
data_gabung

id  kategori_satu kategori_dua kategori_tiga kategori_empat
0     1         lulus       tinggi         besar        panjang
1     2   tidak_lulus       rendah         kecil         pendek
2     3   tidak_lulus       sedang        sedang         sedang
3     4   tidak_lulus       tinggi        sedang        panjang
4     5         lulus       tinggi         besar        panjang
5     6   tidak_lulus       rendah         kecil         sedang
6     7   tidak_lulus       rendah         kecil        panjang
7     8         lulus       rendah         kecil         sedang
8     9   tidak_lulus       tinggi        sedang        panjang
9    10         lulus       rendah         kecil         pendek
10    2   tidak_lulus       rendah         kecil         pendek

In [122]:
data_gabung = data_gabung.apply(preprocessing.LabelEncoder().fit_transform)
data_gabung

id   kategori_satu  kategori_dua  kategori_tiga  kategori_empat
0     0              0             2              0               0
1     1              1             0              1               1
2     2              1             1              2               2
3     3              1             2              2               0
4     4              0             2              0               0
5     5              1             0              1               2
6     6              1             0              1               0
7     7              0             0              1               2
8     8              1             2              2               0
9     9              0             0              1               1
10    1              1             0              1               1

In [134]:
data_test1 = data_gabung.iloc[-1, :]

In [128]:
x = data_gabung.iloc[:-1, :]
y = data_target

In [129]:
model = GaussianNB()
model.fit(x,y)

GaussianNB()

In [137]:
model.predict([data_test1])

array(['tidak'], dtype='<U6')

In [143]:
model.predict(data_test1.values.reshape(1,-1))

array(['tidak'], dtype='<U6')

In [138]:
data_test.reshape(-1,1)

array([[2],
       ['tidak_lulus'],
       ['rendah'],
       ['kecil'],
       ['pendek']], dtype=object)

In [146]:
data_test.reshape(1,-1)

array([[2, 'tidak_lulus', 'rendah', 'kecil', 'pendek']], dtype=object)

In [92]:
# pembagian data training dan data testing
x = mydata3.iloc[:, :-1]
y = mydata3.iloc[:, -1]

In [93]:
y

0    0
1    2
2    0
3    1
4    0
5    2
6    1
7    1
8    0
9    0
Name: target, dtype: int32

In [95]:
x_train, x_test, y_train, y_test = train_test_split(x,y, shuffle=False, test_size=0.1)

In [100]:
# model
model = GaussianNB()

In [101]:
model.fit(x,y)

GaussianNB()

In [103]:
model.predict(x_test)

array([0], dtype=int32)